### PR TITLE
#77 Close fullscreen using the control fix

### PR DESCRIPTION
**Pull request by mderrick**
Inspired by #78 fixing bug #77 but with added tests.

### CODE REVIEW

**Comment by mderrick** [comment]
Inspired by https://github.com/mderrick/react-html5video/pull/78 fixing bug #77 but with added tests.

**Comment by Bram-Zijp** [comment]
I have 2.0.0 but the fullscreen button still only enters fullscreen. Going out doesn't work.

**Comment by mderrick** [comment]
@Bram-Zijp I hadn't deployed it as I was going to bundle in a another fix before deploying. I just released v2.0.1. It's being published as we speak. Let me know if it works.

https://travis-ci.org/mderrick/react-html5video/builds/209022178

**Comment by Bram-Zijp** [comment]
Works like a charm, thanks. Side note; I had to add these styles to get the default player playbar icon to display correctly (they were to small).

```
    ._1CiqE svg {
            width: 100%;
            height: 100%;
        }
```

**Comment by mderrick** [comment]
I wouldn't rely on those classnames as they change per build. For now, I'd add a custom className to the `Video` and target `svgs` from there.

Could you please create an issue with the the exact browser version and I will look on fixing it. Thank you!

**Pull request merged**
