### PR TITLE
Refactored V1 branch for React 16 compatibility

### PR DESCRIPTION
**Pull request by fredvollmer**
React 16 will not support React.createClass or React.propTypes APIs. I know that this project is now focused on the V2 version, but our organization will continue to rely on the V1 branch for the foreseeable future. I thought it might be worth releasing a 1.4.1 version to keep V1 usable into the future.

There were three main refactors performed:
* Components created with `React.createClass` were changed to use ES6 classes.
* The `prop-types` plugin was installed, and `React.propTypes` was replaced with `propTypes'
* A `.babelrc` file was created in order to specify the use of ES7 class properties. (Necessary for the new `propTypes` syntax.)

An overview of the forthcoming breaking changes in React 16 (and the guide I followed in doing this refactor) can be found at https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

### CODE REVIEW

**Comment by mderrick** [comment]
Thanks for this! I have totally deprecated the use of v1 and was not planning on making any further release to this branch. However, I will run this when I get a chance and see if I can do one final v1 release. Much appreciated.

**Comment by natenorberg** [comment]
Is there a chance this could be released? This is one of the components that's holding us up from using fiber and it would be nice to not have to do a major refactor

**Comment by mderrick** [comment]
I'm about to merge https://github.com/mderrick/react-html5video/pull/111 so v2 supports React 16. I'd rather promote people to use the better supported v2 than continue to support v1. Is upgrading a real pain for you?

**Comment by natenorberg** [comment]
We’ve applied quite a few customizations on top of the V1 branch, so we’d like to keep going with that since V2 is quite different being a HoC. It looks great, we just don’t have reason to invest time in the upgrade at this point. I totally understand that you want to push people towards V2, so we can just fork this repo until such a time as we decide to upgrade. Thanks for all your work!

**Comment by abramz** [comment]
@mderrick please merge one of the 2 PRs related to this issue.

It is great that you want people to use v2, but the reality is that introducing breaking changes with no documentation and a trivial example makes it very hard for people to upgrade, especially when we have heavily customized the v1 components.

**Comment by mderrick** [comment]
@abramz I get it. It's just time I really don't have right now. Deploying anything on the v1 branch is a nightmare and I have to verify everything works as desired.

Apologies to any one else who finds themselves here. I will make an effort to tackle this when life allows me.

**Comment by natenorberg** [comment]
If anyone else is in this situation, we're using this fork and haven't had any problems:
```
"react-html5video": "https://github.com/Quiq/react-html5video/tarball//1033e22134b7ca653103fe12a5b74ade4b8815da",
```

**Pull request closed without merging**
