### PR TITLE
properties subscribing to media events are now forwarded the event ob…

### PR DESCRIPTION
**Pull request by Grsmto**
…ject as attribute

Hi!
When subscribing to an event, as on the doc like so:
```
<Video controls autoPlay loop muted
            poster="http://sourceposter.jpg"
            onCanPlayThrough={() => {
                // Do stuff
            }}>
            <source src="http://sourcefile.webm" type="video/webm" />
</Video>
```

...the event handler function doesn't receive the original (actually the React) media event.

Forwarding the event let the user retrieve some datas like for example the original player object (by doing `e.target`) and even the current time for example (in my scenario I needed to subscribe to the `timeUpdate` event and retrieve the current time doing `e.target.currentTime`).
Hope this is usefull.
Thanks!

### CODE REVIEW

**Comment by mderrick** [comment]
👍 Excellent fix, my bad. Can you remove the `dist` file from the PR so its just the fix please? I will merge it in and build that with a deploy commit. Thanks!

**Comment by Grsmto** [comment]
Done!

**Comment by mderrick** [comment]
Sorry, I meant just remove your change, not the whole file! :)

**Comment by Grsmto** [comment]
Omg -_- I just woke up :p haha

**Comment by Grsmto** [comment]
Should be good. Sorry for messing up the git history 😂

**Comment by Angelk90** [comment]
@Grsmto : How can I have the current time always updated without having to click on the controller.

That is, I need to be able to print the time as the video is playing.

Can you give me a hand?

**Pull request merged**
