### PR TITLE
Fix #88 PropTypes deprecation warning

### LINKED ISSUE #88: PropTypes deprecation warning
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### PR DESCRIPTION
**Pull request by yuchuan1**
Fix #88 PropTypes deprecation warning

### CODE REVIEW

**Comment by mderrick** [comment]
Thank you! Is it possible to make `prop-types` a `devDependency` instead? This means it won't install when someone runs`npm install react-html5video`. It shouldn't be needed as we only publish the build distributable. After that I think this is all good to go!

**Comment by mderrick** [comment]
Thanks :)

**Comment by kwangkim** [comment]
I do not think you update the npm library.
I still see the warning.
```
	DefaultPlayer.propTypes = {
	    copy: _react.PropTypes.object.isRequired,
	    controls: _react.PropTypes.arrayOf(_react.PropTypes.oneOf(controls)),
	    video: _react.PropTypes.object.isRequired
	};
```
Could you check the npm library?
I used react-html5video 2.1.0

**Comment by mderrick** [comment]
Yea I've not published yet. Will do ASAP.

**Pull request merged**
