### PR TITLE
Playback Rate

### PR DESCRIPTION
**Pull request by thedeerchild**
Add a method to adjust the playback rate of the video

### CODE REVIEW

**Comment by mderrick** [comment]
So sorry for neglecting this. I've been exceptionally busy. Will try look at it ASAP.

**Comment by philolo1** [comment]
what is the state of this @mderrick is this usable?

**Comment by mderrick** [comment]
Hi @philolo1, it is certainly something I want to include, I just need get round to looking at it. Apologies to the both of you. I will try jump on this as soon as I get a free moment.

**Comment by mderrick** [comment]
@thedeerchild thank you. Sorry for the long, long delay.

**Pull request merged**
