### PR TITLE
Add contribution info to README.md, additional npm build scripts

### PR DESCRIPTION
**Pull request by ypt**
@mderrick, I'm working on getting up to speed to be able to contribute to your project. As a "getting started" exercise for myself, here's a small PR with what I _think_ is your intended dev setup and workflow to work with this project. Please let me know if I'm heading in the right direction.

A few other comments/questions:

- Hot reloading on the local instance of demo site doesn't seem to be working fully as expected. (When running the demo site, making code changes requires executing `npm run build` and then `npm run dev-server` each time in order for the updates to be reflected locally on demo site.)
- It seems like [react-hot-loader](https://github.com/gaearon/react-hot-loader) is currently being phased out in favor of [react-transform](https://github.com/gaearon/react-transform-boilerplate), so I wasn't sure how much effort was worthwhile to invest into react-hot-loader.

### CODE REVIEW

**Comment by ypt** [comment]
I just saw your recent updates - and don't think this PR is relevant any more. I'll close this.

**Comment by mderrick** [comment]
Hey @ypt thanks for this!

I just had a quick go and HMR works for me. I updated the readme with a small section:
https://github.com/mderrick/react-html5video#dev-setup

I will certainly take a look at react-transform when I get a chance.

Let me know if you can get the demo running.

**Comment by ypt** [comment]
Awesome. Running the demo locally and hot reload are working as expected. Thanks for the quick update.

**Comment by mderrick** [comment]
No problem :smile:

**Pull request closed without merging**
